### ISSUE TITLE
Can not find tsserver error on 1.3.8

### ISSUE THREAD

**Issue by mrzzy** [neoclide/coc-tsserver#44]
It appears that the 1.3.8 release has broken `coc-tsserver` for me:
The output of `:CocInfo` on 1.3.8:
```
## versions

vim version: NVIM v0.3.5
node version: v12.2.0
coc.nvim version: 0.0.71-4ee27ce232
term: screen-256color
platform: linux

## Messages
[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!
```
This happens when I open a JS file using `nvim test.js`
I have tried to do `:CocInstall coc-tsserver` to no avail.
Using vim-plug also does not solve the problem:
```
Plug 'neoclide/coc-tsserver', {'tag': '1.3.8', 'do': 'yarn install --frozen-lockfile'} 
```

On downgrade to 1.3.7 using vim-plug the error does not appear and the extension works flawlessly:
```
Plug 'neoclide/coc-tsserver', {'tag': '1.3.7', 'do': 'yarn install --frozen-lockfile'} 
```

**Comment by clark-t** [comment]
same problem...

**Comment by abdesselame17** [comment]
Same problem, this is the output of CocInfo: 
```## versions

vim version: NVIM v0.3.7
node version: v10.16.0
coc.nvim version: 0.0.71
term: screen-256color
platform: linux

## Messages[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!
extension coc-tsserver installed!
```

**Comment by abdesselame17** [comment]
Same problem, this is the output of CocInfo: 
```## versions

vim version: NVIM v0.3.7
node version: v10.16.0
coc.nvim version: 0.0.71
term: screen-256color
platform: linux

## Messages[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!
extension coc-tsserver installed!
```

**Comment by abdesselame17** [comment]
Same problem, this is the output of CocInfo: 
```## versions

vim version: NVIM v0.3.7
node version: v10.16.0
coc.nvim version: 0.0.71
term: screen-256color
platform: linux

## Messages[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!
extension coc-tsserver installed!
```

**Comment by abdesselame17** [comment]
Same problem, this is the output of CocInfo: 
```## versions

vim version: NVIM v0.3.7
node version: v10.16.0
coc.nvim version: 0.0.71
term: screen-256color
platform: linux

## Messages[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!
extension coc-tsserver installed!
```

**Comment by vikahl** [comment]
Same problem, with the following `:CocInfo`

```
## versions

vim version: NVIM v0.3.4
node version: v10.15.2
coc.nvim version: 0.0.71-4ee27ce232
term: xterm-256color
platform: linux

## Messages
[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!
```

**Comment by chemzqm** [comment]
Fixed on 1.3.9

**Comment by spagy** [comment]
I'm having the same issue with 1.3.14 of coc-tsserver

```
## versions

vim version: NVIM v0.3.4
node version: v10.15.2
coc.nvim version: 0.0.73-8b9b7d83a6
term: xterm-256color
platform: linux

## Messages[coc.nvim] Bundled typescript module not found
[coc.nvim] Can not find typescript module, run ':CocInstall coc-tsserver' to fix it!

```

**Comment by chemzqm** [comment]
Try reinstall, could be issues with your npm.

**Comment by spagy** [comment]
I've just deleted everything related to coc, reinstalled coc and then installed coc-tsserver. Unfortunately I seem to still get the same error.

**Comment by chemzqm** [comment]
Run `npm install` in the folder of coc-tsserver, I don't know why it failed to install dependencies for you.

**Comment by spagy** [comment]
aah that didn't work but it showed be that i had a load of permissions problems with node. i've fixed those and everything is working perfectly now. sorry about the hassle.

thanks for your help and your speedy responses :)

**Comment by XueshiQiao** [comment]
I encounter the same problem, here is the log

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/joey/.nvm/versions/node/v10.17.0/bin/node',
1 verbose cli   '/Users/joey/.nvm/versions/node/v10.17.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'typescript',
1 verbose cli   '--verbose' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose npm-session 90fe9de7710d8144
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/typescript 1084ms (from cache)
8 silly fetchPackageMetaData error for typescript@3.7.3 Unexpected end of JSON input while parsing near '...del":"latest","gulp":'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 1134ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...del":"latest","gulp":'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/Users/joey/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/Users/joey/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /Users/joey/.config/coc/extensions/node_modules/coc-tsserver
13 verbose Darwin 19.0.0
14 verbose argv "/Users/joey/.nvm/versions/node/v10.17.0/bin/node" "/Users/joey/.nvm/versions/node/v10.17.0/bin/npm" "install" "typescript" "--verbose"
15 verbose node v10.17.0
16 verbose npm  v6.11.3
17 error Unexpected end of JSON input while parsing near '...del":"latest","gulp":'
18 verbose exit [ 1, true ]
```

Log shows it got errors when installing typescript, and after I googled some pages, I fixed the problem by cleaned the npm cache. Any guys encounter same problem maybe have a try:

```
npm cache clean --force
```

**Comment by therealplato** [comment]
I'm experiencing this issue on 1.4.15.
From `:CocInfo`:
```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 27 2020 16:15:44)
node version: v12.16.1
coc.nvim version: 0.0.78-eb5bbfad09
term: dumb
platform: linux
```

from `:messages`:
```
[coc.nvim] Can not find typescript module, run ':CocInstall coc-tsserver' to fix it!
[coc.nvim] Bundled typescript module not found
```
I did see a green success message one time after running `:CocInstall coc-tsserver` but subsequent runs continue to fail. I'm not sure what the difference was.
All other times I have run `:CocInstall coc-tsserver` from within a .tsx buffer, I get:
```
[coc.nvim] Can not find typescript module, run ':CocInstall coc-tsserver' to fix it!
```
And when I run it from a non-tsx buffer, I get:
```
[coc.nvim] Bundled typescript module not found
```

My `~/.config/coc/extensions/node_modules/coc-tsserver/ ` folder has no `node_modules` child.
Running `npm install` in that folder fails with:
```
internal/modules/cjs/loader.js:985
  throw err;
  ^
Error: Cannot find module '../lib/utils/unsupported.js'
```

The way I first installed coc-tsserver was _not_ with the `:CocInstall coc-tsserver` command, but by placing these lines in my vimrc and running `:PlugInstall` :
```
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
...
let g:coc_global_extensions = [ 'coc-tsserver' ]
```

**Comment by chemzqm** [comment]
You need to run `npm install --production --ignore-scripts` to avoid build source code.

**Comment by therealplato** [comment]
Thanks @chemzqm - my issue ended up being a broken npm installation

**Comment by steelx** [comment]
im also having same issue. I just install npm. 
Neovim:
`coc-tsserver /snap/bin/npm install exited with 243`

**Comment by chemzqm** [comment]
Looks like your need configure `npm.binPath` configuration.

**Comment by juanMarinero** [comment]
hi @steelx , I had same error (with `coc-sh`), it was the installer
Uninstall `node` from `snap`
`sudo snap remove node`
and install it through `apt-get` (or `.tar`,... [official link](https://nodejs.org/en/download/))
`sudo apt-get install nodejs`

With `snap` and `:CocInstall {whatever}` the `coc.nvim` installer reports:
`Using npm from: /snap/bin/npm`
While with `apt-get` and `:CocInstall {whatever}`:
`Using npm from: /usr/local/bin/yarnpkg`

**Comment by Shafin098** [comment]
> I encounter the same problem, here is the log
> 
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/Users/joey/.nvm/versions/node/v10.17.0/bin/node',
> 1 verbose cli   '/Users/joey/.nvm/versions/node/v10.17.0/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   'typescript',
> 1 verbose cli   '--verbose' ]
> 2 info using npm@6.11.3
> 3 info using node@v10.17.0
> 4 verbose npm-session 90fe9de7710d8144
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 304 https://registry.npmjs.org/typescript 1084ms (from cache)
> 8 silly fetchPackageMetaData error for typescript@3.7.3 Unexpected end of JSON input while parsing near '...del":"latest","gulp":'
> 9 timing stage:rollbackFailedOptional Completed in 1ms
> 10 timing stage:runTopLevelLifecycles Completed in 1134ms
> 11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...del":"latest","gulp":'
> 11 verbose stack     at JSON.parse (<anonymous>)
> 11 verbose stack     at parseJson (/Users/joey/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
> 11 verbose stack     at consumeBody.call.then.buffer (/Users/joey/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
> 11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
> 12 verbose cwd /Users/joey/.config/coc/extensions/node_modules/coc-tsserver
> 13 verbose Darwin 19.0.0
> 14 verbose argv "/Users/joey/.nvm/versions/node/v10.17.0/bin/node" "/Users/joey/.nvm/versions/node/v10.17.0/bin/npm" "install" "typescript" "--verbose"
> 15 verbose node v10.17.0
> 16 verbose npm  v6.11.3
> 17 error Unexpected end of JSON input while parsing near '...del":"latest","gulp":'
> 18 verbose exit [ 1, true ]
> ```
> 
> Log shows it got errors when installing typescript, and after I googled some pages, I fixed the problem by cleaned the npm cache. If you guys encounter same problem maybe have a try:
> 
> ```
> npm cache clean --force
> ```

Cleaning cache fixed the issue
